using Bogcha.DataAccess.Repositories.AssessmentRecNurseryRepositories;

namespace Bogcha.Services.Services.AssessmentRecNurseryServices;

public interface IAssessmentRecNurseryService:IAssessmentRecNurseryRepository
{
}
